version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    container_name: app
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/warehouse
      SPRING_DATASOURCE_USERNAME: compose-postgres
      SPRING_DATASOURCE_PASSWORD: compose-postgres
  postgres:
    image: 'postgres:15-alpine'
    environment:
      POSTGRES_DB: warehouse
      POSTGRES_USER: compose-postgres
      POSTGRES_PASSWORD: compose-postgres
    ports:
      - "5432:5432"

volumes:
  data: