apiVersion: v1
kind: ConfigMap
metadata:
  name: product-configmap
  namespace: myspace
data:
  PROFILES: "prod"
  DATABASE_NAME: "mediasoft_test"
  DATABASE_URL: "jdbc:postgresql://postgresql-productk8s-postgres-service:5432"
  DATABASE_SCHEMA: "public"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "password"