apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: productk8s-postgresql
  namespace: myspace
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: productk8s-postgresql
  template:
    metadata:
      labels:
        app: productk8s-postgresql
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
              name: postgredb
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: product-configmap
                  key: DATABASE_NAME
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: product-configmap
                  key: SPRING_DATASOURCE_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: product-configmap
                  key: SPRING_DATASOURCE_PASSWORD
          volumeMounts:
            - name: postgredb
              mountPath: /var/lib/postgresql/data
              subPath: postgres
  volumeClaimTemplates:
    - metadata:
        name: postgredb
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-productk8s-postgres-service
  namespace: myspace
spec:
  selector:
    app: productk8s-postgresql
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  type: ClusterIP
#  clusterIP: None
