apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
data:
  DATABASE_NAME: {{ .Values.service.db.dbname | b64enc }}
  DATABASE_SCHEMA: {{ .Values.service.db.dbschema | b64enc }}
  DATABASE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXNxbC1wcm9kdWN0azhzLXBvc3RncmVzLXNlcnZpY2U6NTQzMg== #jdbc:postgresql://postgresql-productk8s-postgres-service:5432
  SPRING_DATASOURCE_USERNAME: cG9zdGdyZXM= #postgres
  SPRING_DATASOURCE_PASSWORD: cGFzc3dvcmQ= #password
