spring:
  datasource:
    url: jdbc:h2:mem:mediasoft_test
    username: sa
    password: ${PWD}
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
      database-platform: org.hibernate.dialect.H2Dialect
      properties:
        hibernate.format_sql: true

  h2:
    console:
      enabled: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml