spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mediasoft_test
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver

  jpa:
    properties:
      hibernate.format_sql: false
    show-sql: false
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml