spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mediasoft_test
    username: postgres
    password: ${PWD}
    driverClassName: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: validate

    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

app:
  scheduling:
    enabled: false
    period: 60000 #ms
    priceIncreasePercentage: 10.1
    optimization: true

rest:
  currency-service:
    mock:
      enabled: false
    host: http://localhost:8081 #хост второго сервиса
    methods:
      get-currency: /currencies #урл эндпоинта с курсами для GET запроса

  account-service:
    mock:
      enabled: true
    host: http://localhost:8082 #хост сервиса аккаунтов
    methods:
      get-account: /account #урл эндпоинта с аккаунтами для GET запроса

  crm-service:
    mock:
      enabled: true
    host: http://localhost:8083 #хост CRM сервиса
    methods:
      get-inn: /crm #урл эндпоинта с ИНН для GET запроса