spring:
  datasource:
    url: jdbc:h2:mem:mediasoft_test
    username: sa
    password: ${PWD}
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.H2Dialect
      properties:
        hibernate.format_sql: true

  h2:
    console:
      enabled: true

  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.xml

rest:
  currency-service:
    mock:
      enabled: false
    #    host: ${CURRENCY_URL:http://localhost:8081} #хост сервиса валют
    host: ${CURRENCY_URL:http://currency-service.myspace.svc.cluster.local:8080} #хост сервиса валют
    methods:
      get-currency: /currencies #урл эндпоинта с курсами для GET запроса

  account-service:
    mock:
      enabled: false
    #    host: ${ACCOUNT_URL:http://localhost:8082} #хост сервиса аккаунтов
    host: ${ACCOUNT_URL:http://account-service.myspace.svc.cluster.local:8080} #хост сервиса аккаунтов
    methods:
      get-account: /account #урл эндпоинта с аккаунтами для GET запроса

  crm-service:
    mock:
      enabled: false
    #    host: ${CRM_URL:http://localhost:8083} #хост CRM сервиса
    host: ${CRM_URL:http://crm-service.myspace.svc.cluster.local:8080} #хост CRM сервиса
    methods:
      get-inn: /crm #урл эндпоинта с ИНН для GET запроса

  camunda-service:
    mock:
      enabled: false
    #    host: ${CRM_URL:http://localhost:8084} #хост CRM сервиса
    host: ${CAMUNDA_URL:http://localhost:8084} #хост CRM сервиса
    methods:
      start-confirm: confirm/start #урл эндпоинта с ИНН для GET запроса