apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: myspace
spec:
  selector:
    app: account-pod #должно соответствовать лейблу пода
  ports:
    - protocol: TCP
      name: web
      port: 8080 #порт сервиса
      targetPort: 8082 #порт пода (порт, который открыт для контейнера)
  type: ClusterIP
