apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: myspace
spec:
  selector:
    app: product-app #должно соответствовать лейблу пода
  ports:
    - protocol: TCP
      name: web
      port: 8080 #порт сервиса
      targetPort: 8080 #порт пода (порт, который открыт для контейнера)
  type: ClusterIP
